services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgre
    environment:
      MYSQL_DATABASE: gestion_produits
      MYSQL_ROOT_PASSWORD: root